### PR TITLE
Added more catch-phrases

### PR DESCRIPTION
**Pull request by taraldga**
More ideas forming, stay in touch for delicious PR's.

### CODE REVIEW

**Comment by damsleth** [comment]
@taraldga 
Gotta slash those endpoints, boy.
"/mmm" && "/hi"

**Comment by taraldga** [comment]
Is this a thing against women and christians?

**Comment by damsleth** [comment]
Yes.
No, but you have to prefix the endpoint-url with a slash, like so
``` app.get('/hi', (req, res) => { res.json({ message: "Hi!" }) }) ```
instead of 
``` app.get('hi', (req, res) => { res.json({ message: "Hi!" }) }) ```

**Comment by taraldga** [comment]
Ohh, right on. 

We here have a classic case of the "Commit-before-save-sies". Another commit coming up.

**Comment by damsleth** [comment]
👏

**Pull request merged**
